using 'main.bicep'

param location = 'brazilsouth'
param resourceGroupName = 'rg-hml-br-ifrisk'
param vnetName = 'vn-hml-br-ifrisk'
param vnetAddressPrefix = '172.24.58.0/23'
param publicSubnetCidr = '172.24.58.0/24'
param privateSubnetCidr = '172.24.59.0/24'
param databricksWorkspaceName = 'adb-hml-br-ifrisk'
param workerIdentityName = 'umi-worker-southbr-hml-0001'
